baseurl = ""
title = "Azure Heroes"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"
summaryLength = 70
buildFuture = true

[menu]
# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = "/events/"
    weight     = 5

[[menu.main]]
    identifier = "menu.sponsors"
    name       = "Sponsors"
    url        = "/sponsors/"
    weight     = 6

[[menu.main]]
    identifier = "menu.speakers"
    name       = "CFP"
    url        = "/CFP/"
    weight     = 7

[[menu.main]]
    identifier = "menu.code"
    name       = "Code of Conduct"
    url        = "/codeofconduct/"
    weight     = 8

[[menu.main]]
    identifier = "team"
    name       = "Team"
    url        = "/team/"
    weight     = 9

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 10

# Top bar social links menu
[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/azure-heroes"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[params]
    noComment = true 
    viewMorePostLink = "/events/"
    author = "Azure Heroes"
    defaultKeywords = ["Azure Heroes", "Cloud", "Azure"]
    mainSections = ["events"]
    defaultDescription = "Azure Heroes - Learn from Azure Heroes, Network and be part of a community."

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    contact_form_ajax = true

    #forms
    contact_action = "https://prod-79.westeurope.logic.azure.com:443/workflows/a7dc7d87b98e4042b14908726acc17b9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=hzPTBm4zcqXLV5Htt68zM3z37nRllXZePH1Mf_-y9pE"

    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "6LfaxtohAAAAAELRkS4CT4Dm0SPlc6Ttr4e48xIJ"

    about_us = "<p>Azure Heroes is a user group that focuses on Cloud Technologies. The group was founded in 2018 by an IT enthusiast.</p>"
    copyright = "Copyright (c) 2025, Azure Heroes; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "Azure Heroes"

    logo = "img/logo-small.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
  

[permalinks]
    events = "/events/:year/:month/:day/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    tags = true
    search = true

[params.carouselCustomers]
    items = 3
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 3
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.testimonials]
    enable = true
    title = "Team"
    subtitle = ""

[params.team]
    enable = true
    title = "Team"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-bell"
    title = "Our Next Event - In - Person!"
    subtitle = "30 September - Azure Heroes NL @ Rubicon!"
    link_url = "/events/2025/09/30/"
    link_text = "Register Now"

[params.clients]
    enable = true
    title = "Sponsors"
    subtitle = ""

[params.sponsors]
    enable = true
    title = "Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"